declare namespace chrome {
    ////////////////////
    // Enterprise Device Attributes
    ////////////////////
    /**
     * Use the `chrome.enterprise.deviceAttributes` API to read device attributes.
     *
     * Permissions: "enterprise.deviceAttributes"
     *
     * Note: Only available to policy installed extensions.
     * @platform ChromeOS only
     * @since Chrome 46
     */
    namespace enterprise.deviceAttributes {
        /**
         * Fetches the value of the device identifier of the directory API, that is generated by the server and identifies the cloud record of the device for querying in the cloud directory API. If the current user is not affiliated, returns an empty string.
         *
         * Can return its result via Promise in Manifest V3 or later since Chrome 96.
         */
        function getDirectoryDeviceId(): Promise<string>;
        function getDirectoryDeviceId(callback: (deviceId: string) => void): void;

        /**
         * Fetches the device's serial number. Please note the purpose of this API is to administrate the device (e.g. generating Certificate Sign Requests for device-wide certificates). This API may not be used for tracking devices without the consent of the device's administrator. If the current user is not affiliated, returns an empty string.
         *
         * Can return its result via Promise in Manifest V3 or later since Chrome 96.
         * @since Chrome 66
         */
        function getDeviceSerialNumber(): Promise<string>;
        function getDeviceSerialNumber(callback: (serialNumber: string) => void): void;

        /**
         * Fetches the administrator-annotated Asset Id. If the current user is not affiliated or no Asset Id has been set by the administrator, returns an empty string.
         *
         * Can return its result via Promise in Manifest V3 or later since Chrome 96.
         * @since Chrome 66
         */
        function getDeviceAssetId(): Promise<string>;
        function getDeviceAssetId(callback: (assetId: string) => void): void;

        /**
         * Fetches the administrator-annotated Location. If the current user is not affiliated or no Annotated Location has been set by the administrator, returns an empty string.
         *
         * Can return its result via Promise in Manifest V3 or later since Chrome 96.
         * @since Chrome 66
         */
        function getDeviceAnnotatedLocation(): Promise<string>;
        function getDeviceAnnotatedLocation(callback: (annotatedLocation: string) => void): void;

        /**
         * Fetches the device's hostname as set by DeviceHostnameTemplate policy. If the current user is not affiliated or no hostname has been set by the enterprise policy, returns an empty string.
         *
         * Can return its result via Promise in Manifest V3 or later since Chrome 96.
         * @since Chrome 82
         */
        function getDeviceHostname(): Promise<string>;
        function getDeviceHostname(callback: (hostname: string) => void): void;
    }
}
