/// <reference path="./chrome-cast/index.d.ts" />
/// <reference path="./namespaces/accessibilityFeatures.d.ts" />
/// <reference path="./namespaces/action.d.ts" />
/// <reference path="./namespaces/alarms.d.ts" />
/// <reference path="./namespaces/audio.d.ts" />
/// <reference path="./namespaces/bookmarks.d.ts" />
/// <reference path="./namespaces/browserAction.d.ts" />
/// <reference path="./namespaces/browsingData.d.ts" />
/// <reference path="./namespaces/certificateProvider.d.ts" />
/// <reference path="./namespaces/commands.d.ts" />
/// <reference path="./namespaces/contentSettings.d.ts" />
/// <reference path="./namespaces/contextMenus.d.ts" />
/// <reference path="./namespaces/cookies.d.ts" />
/// <reference path="./namespaces/debugger.d.ts" />
/// <reference path="./namespaces/declarativeContent.d.ts" />
/// <reference path="./namespaces/declarativeWebRequest.d.ts" />
/// <reference path="./namespaces/desktopCapture.d.ts" />
/// <reference path="./namespaces/devtools.inspectedWindow.d.ts" />
/// <reference path="./namespaces/devtools.network.d.ts" />
/// <reference path="./namespaces/devtools.performance.d.ts" />
/// <reference path="./namespaces/devtools.panels.d.ts" />
/// <reference path="./namespaces/devtools.recorder.d.ts" />
/// <reference path="./namespaces/documentScan.d.ts" />
/// <reference path="./namespaces/dom.d.ts" />
/// <reference path="./namespaces/downloads.d.ts" />
/// <reference path="./namespaces/enterprise.platformKeys.d.ts" />
/// <reference path="./namespaces/enterprise.deviceAttributes.d.ts" />
/// <reference path="./namespaces/enterprise.hardwarePlatform.d.ts" />
/// <reference path="./namespaces/enterprise.login.d.ts" />
/// <reference path="./namespaces/enterprise.networkingAttributes.d.ts" />
/// <reference path="./namespaces/events.d.ts" />
/// <reference path="./namespaces/extension.d.ts" />
/// <reference path="./namespaces/extensionTypes.d.ts" />
/// <reference path="./namespaces/fileBrowserHandler.d.ts" />
/// <reference path="./namespaces/fileSystemProvider.d.ts" />
/// <reference path="./namespaces/fontSettings.d.ts" />
/// <reference path="./namespaces/gcm.d.ts" />
/// <reference path="./namespaces/history.d.ts" />
/// <reference path="./namespaces/i18n.d.ts" />
/// <reference path="./namespaces/identity.d.ts" />
/// <reference path="./namespaces/idle.d.ts" />
/// <reference path="./namespaces/input.ime.d.ts" />
/// <reference path="./namespaces/instanceID.d.ts" />
/// <reference path="./namespaces/loginState.d.ts" />
/// <reference path="./namespaces/management.d.ts" />
/// <reference path="./namespaces/notifications.d.ts" />
/// <reference path="./namespaces/offscreen.d.ts" />
/// <reference path="./namespaces/omnibox.d.ts" />
/// <reference path="./namespaces/pageAction.d.ts" />
/// <reference path="./namespaces/pageCapture.d.ts" />
/// <reference path="./namespaces/permissions.d.ts" />
/// <reference path="./namespaces/platformKeys.d.ts" />
/// <reference path="./namespaces/power.d.ts" />
/// <reference path="./namespaces/printerProvider.d.ts" />
/// <reference path="./namespaces/printing.d.ts" />
/// <reference path="./namespaces/printingMetrics.d.ts" />
/// <reference path="./namespaces/privacy.d.ts" />
/// <reference path="./namespaces/proxy.d.ts" />
/// <reference path="./namespaces/readingList.d.ts" />
/// <reference path="./namespaces/search.d.ts" />
/// <reference path="./namespaces/runtime.d.ts" />
/// <reference path="./namespaces/scripting.d.ts" />
/// <reference path="./namespaces/sessions.d.ts" />
/// <reference path="./namespaces/storage.d.ts" />
/// <reference path="./namespaces/system.cpu.d.ts" />
/// <reference path="./namespaces/system.memory.d.ts" />
/// <reference path="./namespaces/system.storage.d.ts" />
/// <reference path="./namespaces/system.display.d.ts" />
/// <reference path="./namespaces/systemLog.d.ts" />
/// <reference path="./namespaces/tabCapture.d.ts" />
/// <reference path="./namespaces/tabs.d.ts" />
/// <reference path="./namespaces/tabGroups.d.ts" />
/// <reference path="./namespaces/topSites.d.ts" />
/// <reference path="./namespaces/tts.d.ts" />
/// <reference path="./namespaces/ttsEngine.d.ts" />
/// <reference path="./namespaces/types.d.ts" />
/// <reference path="./namespaces/vpnProvider.d.ts" />
/// <reference path="./namespaces/wallpaper.d.ts" />
/// <reference path="./namespaces/webAuthenticationProxy.d.ts" />
/// <reference path="./namespaces/webNavigation.d.ts" />
/// <reference path="./namespaces/webRequest.d.ts" />
/// <reference path="./namespaces/windows.d.ts" />
/// <reference path="./namespaces/declarativeNetRequest.d.ts" />
/// <reference path="./namespaces/sidePanel.d.ts" />
/// <reference path="./namespaces/userScripts.d.ts" />
// Helpers
type SetRequired<T, K extends keyof T> = Omit<T, K> & Required<Pick<T, K>>;
type SetPartial<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>;

////////////////////
// Global object
////////////////////
interface Window {
    chrome: typeof chrome;
}
